### ISSUE TITLE
installer erros after creating partitions | panic: Trying to run MakeFs() against a disk, partition required

### ISSUE THREAD

**Issue by mrkz** [clearlinux/clr-installer#179]
**Describe the bug**

![disk_scheme](https://user-images.githubusercontent.com/978752/49399796-e7c3ca00-f707-11e8-91d8-87a37707b3ae.png)

After creating the following disk scheme and starting with the installation, the installer throws the following error and exits:
```
# /usr/bin/clr-installer -l 4
panic: Trying to run MakeFs() against a disk, partition required

Error Trace:
storage.(*BlockDevice).MakeFs()
     storage/ops.go:57
controller.Install()
     controller/controller.go:229


goroutine 37 [running]:
github.com/clearlinux/clr-installer/tui.(*Tui).Run(0xc000131020, 0xc000001e00, 0xc000028f80, 0x16, 0x100, 0xc000028ee0, 0x17, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/clr-installer-1.1.0/.gopath/src/github.com/clearlinux/clr-installer/tui/tui.go:162 +0x670
main.main.func4(0xc0000b90e0, 0xc000001e00, 0xc000028f80, 0x16, 0xc000292995, 0xc00006db50, 0xc00007e0e0)
	/builddir/build/BUILD/clr-installer-1.1.0/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:243 +0x168
created by main.main
	/builddir/build/BUILD/clr-installer-1.1.0/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:237 +0x93d

```

**To Reproduce**
1. Set up the partition scheme to the one shown in the picture before
2. Continue with the installation

**Expected behavior**
Create the partitions and continue with the install process normally

**Environment (please complete the following information):**
 - Clear Linux OS Version: 26630
 - Installer Version: `clr-installer: 1.1.0`
 - Platform: NUC

**Additional context**
Here's the log I've got:
```
# cat clr-installer.log 
2018/12/03 14:13:56 [DBG] Log Level set to LogLevelDebug (4)
2018/12/03 14:13:56 [INF] clr-installer: 1.1.0, built on 2018-11-30_18:09:00_UTC
2018/12/03 14:13:56 [DBG] Loading config file: /var/lib/clr-installer/clr-installer.yaml
2018/12/03 14:13:56 [DBG] PrivateIP: Found IP: 10.54.69.24, Private IP?: true
2018/12/03 14:13:56 [INF] NOTICE: Enabling Telemetry preferred by default on internal networks
2018/12/03 14:13:56 [DBG] localectl list-keymaps --no-pager
2018/12/03 14:13:56 [DBG] timedatectl list-timezones
2018/12/03 14:13:56 [DBG] locale -a
2018/12/03 14:13:56 [DBG] Unable to use language locale 'agr_PE.UTF-8'
2018/12/03 14:13:56 [DBG] Unable to use language locale 'ayc_PE.UTF-8'
2018/12/03 14:13:56 [DBG] Unable to use language locale 'ber_DZ.UTF-8'
2018/12/03 14:13:56 [DBG] Unable to use language locale 'ber_MA.UTF-8'
2018/12/03 14:13:56 [DBG] Unable to use language locale 'bhb_IN.UTF-8'
2018/12/03 14:13:56 [DBG] Unable to use language locale 'hne_IN.UTF-8'
2018/12/03 14:13:56 [DBG] Unable to use language locale 'miq_NI.UTF-8'
2018/12/03 14:13:56 [DBG] Unable to use language locale 'mjw_IN.UTF-8'
2018/12/03 14:13:56 [DBG] Unable to use language locale 'nhn_MX.UTF-8'
2018/12/03 14:13:56 [DBG] Unable to use language locale 'shs_CA.UTF-8'
2018/12/03 14:13:56 [DBG] Unable to use language locale 'the_NP.UTF-8'
2018/12/03 14:13:56 [DBG] Unable to use language locale 'unm_US.UTF-8'
2018/12/03 14:13:56 [DBG] Unable to use language locale 'yuw_PG.UTF-8'
2018/12/03 14:13:56 [DBG] lsblk --exclude 1,2,11 -J -b -O
2018/12/03 14:13:56 [DBG] partprobe /dev/sda
2018/12/03 14:13:56 [DBG] partprobe /dev/sdb
2018/12/03 14:13:56 [DBG] Warning: Not all of the space available to /dev/sdb appears to be used, you can fix the GPT to use all of the space (an extra 13533184 blocks) or continue with the current setting? 
2018/12/03 14:13:56 [DBG] ip route show
2018/12/03 14:13:56 [DBG] ip route show default
2018/12/03 14:13:56 [DBG] ip route show
2018/12/03 14:13:56 [DBG] ip route show default
2018/12/03 14:14:11 [DBG] ip route show
2018/12/03 14:14:11 [DBG] ip route show default
2018/12/03 14:14:11 [DBG] ip route show
2018/12/03 14:14:11 [DBG] ip route show default
2018/12/03 14:17:01 [DBG] ip route show
2018/12/03 14:17:01 [DBG] ip route show default
2018/12/03 14:17:01 [DBG] ip route show
2018/12/03 14:17:01 [DBG] ip route show default
2018/12/03 14:17:30 [INF] Testing connectivity
2018/12/03 14:17:30 [DBG] timeout --kill-after=10s 10s curl --no-sessionid -o /dev/null -s -f https://cdn.download.clearlinux.org/update/
2018/12/03 14:17:33 [DBG] ip route show
2018/12/03 14:17:33 [DBG] ip route show default
2018/12/03 14:17:33 [DBG] ip route show
2018/12/03 14:17:33 [DBG] ip route show default
2018/12/03 14:18:07 [DBG] ip route show
2018/12/03 14:18:07 [DBG] ip route show default
2018/12/03 14:18:07 [DBG] ip route show
2018/12/03 14:18:07 [DBG] ip route show default
2018/12/03 14:19:00 [DBG] ip route show
2018/12/03 14:19:00 [DBG] ip route show default
2018/12/03 14:19:00 [DBG] ip route show
2018/12/03 14:19:00 [DBG] ip route show default
2018/12/03 14:19:08 [DBG] ip route show
2018/12/03 14:19:08 [DBG] ip route show default
2018/12/03 14:19:08 [DBG] ip route show
2018/12/03 14:19:08 [DBG] ip route show default
2018/12/03 14:19:19 [INF] Running pre-install hooks
2018/12/03 14:19:19 [DBG] Created Local Telemetry server configuration file "/etc/telemetrics/telemetrics.conf"
2018/12/03 14:19:19 [DBG] telemctl restart
2018/12/03 14:19:19 [INF] Querying Clear Linux version
2018/12/03 14:19:19 [DBG] Clear Linux version: 26630
2018/12/03 14:19:19 [INF] Writing partition table to: sda
2018/12/03 14:19:19 [DBG] parted -s /dev/sda mklabel gpt
2018/12/03 14:19:19 [DBG] parted -a optimal /dev/sda --script mkpart EFI fat32 0M 500M mkpart eswap500 500M 16884M mkpart / 16884M 272884M mkpart /srv 272884M 354804M mkpart /home 354804M 457862M
2018/12/03 14:19:19 [DBG] Warning: The resulting partition is not properly aligned for best performance.
2018/12/03 14:19:19 [DBG] parted /dev/sda set 1 boot on
2018/12/03 14:19:19 [DBG] Information: You may need to update /etc/fstab.
                                                                          
2018/12/03 14:19:21 [INF] Adjusting filesystem configurations
2018/12/03 14:19:21 [DBG] sgdisk /dev/sda --typecode=1:C12A7328-F81F-11D2-BA4B-00A0C93EC93B
2018/12/03 14:19:22 [DBG] The operation has completed successfully.
2018/12/03 14:19:22 [DBG] sgdisk /dev/sda --typecode=3:4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709
2018/12/03 14:19:24 [DBG] The operation has completed successfully.
2018/12/03 14:19:24 [DBG] sgdisk /dev/sda --typecode=4:3B8F8425-20E0-4F3B-907F-1A25A76F98E8
2018/12/03 14:19:26 [DBG] The operation has completed successfully.
2018/12/03 14:19:26 [DBG] sgdisk /dev/sda --typecode=5:933AC7E1-2EB4-4F13-B844-0E14E2AEF915
2018/12/03 14:19:27 [DBG] The operation has completed successfully.
2018/12/03 14:19:27 [DBG] partprobe /dev/sda
2018/12/03 14:19:31 [INF] Writing vfat file system to sda1 '/boot'
2018/12/03 14:19:31 [ERR] 

Error Trace:
storage.(*BlockDevice).MakeFs()
     storage/ops.go:57
controller.Install()
     controller/controller.go:229
 Trying to run MakeFs() against a disk, partition required
2018/12/03 14:19:31 [DBG] telem-record-gen --severity 3 --class org.clearlinux/clr-installer/tuipanic --event-id ef17f161eb26e66a0818f838437f2923 --payload version=1.1.0
Trying to run MakeFs() against a disk, partition required

Error Trace:
storage.(*BlockDevice).MakeFs()
     storage/ops.go:57
controller.Install()
     controller/controller.go:229
```

**Comment by mrkz** [comment]
@mdhorn I've pulled master and tried again, I'm still reproducing the same issue ;-(.

reproducing with the same input as above in the bug report. I'm also having the same panic output. (I see `[Clear Linux* OS Installer (1.1.1)]` in the version) fwiw.

**Comment by mdhorn** [comment]
@mrkz You are seeing the same `storage.(*BlockDevice).MakeFs()`?
Or are you seeing the error about partitioning reported in #182 ?

**Comment by mrkz** [comment]
Same issue as reported here.

**Comment by mdhorn** [comment]
@mrkz  Please run with -l 4 and attach the complete log file for me. I can not reproduce that error after the fix.
