### ISSUE TITLE
installer panics when installing on a partition disk scheme where one partition is not set to any mount-point

### ISSUE THREAD

**Issue by mrkz** [clearlinux/clr-installer#182]
**Describe the bug**
As described in the workaround from https://github.com/clearlinux/clr-installer/issues/180, using `cgdisk` I formatted the disk into 5 partitions, where 4 are used by the `clr-installer` and one is left intact by the installer, apparently this causes the installer to panics with the following error:
```
# /usr/bin/clr-installer -l 4
panic: No makePartCommand() implementation for: 

Error Trace:
storage.(*BlockDevice).WritePartitionTable()
     storage/ops.go:207
controller.Install()
     controller/controller.go:203


goroutine 7 [running]:
github.com/clearlinux/clr-installer/tui.(*Tui).Run(0xc0001551a0, 0xc00008cc00, 0xc0000b0d80, 0x16, 0x100, 0xc0000b0ce0, 0x17, 0x0, 0x0, 0x0, ...)
        /builddir/build/BUILD/clr-installer-1.1.0/.gopath/src/github.com/clearlinux/clr-installer/tui/tui.go:162 +0x670
main.main.func4(0xc0000cf7a0, 0xc00008cc00, 0xc0000b0d80, 0x16, 0xc000296a75, 0xc0000a3b40, 0xc0001a4070)
        /builddir/build/BUILD/clr-installer-1.1.0/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:243 +0x168
created by main.main
        /builddir/build/BUILD/clr-installer-1.1.0/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:237 +0x93d
```

This is the disk scheme I've used (sda4 is not used for the CLR installation):

![disk_scheme](https://user-images.githubusercontent.com/978752/49407382-0b920a80-f71e-11e8-8b8a-9dbbb7c84602.png)

**To Reproduce**
1. Create a partition scheme as shown in image previously shown
2. Click on the `install` button to begin installation
3. See error

**Expected behavior**
Installer should be able to continue with the installation

**Environment (please complete the following information):**
 - Clear Linux OS Version: 26630
 - Installer Version: clr-installer: 1.1.0
 - Platform: NUC

**Aditional context**

This is the log and the partitions before/after running the installer:
```
# lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 447.1G  0 disk
├─sda1   8:1    0   500M  0 part
├─sda2   8:2    0    16G  0 part
├─sda3   8:3    0   250G  0 part
├─sda4   8:4    0    80G  0 part
└─sda5   8:5    0 100.7G  0 part

# /usr/bin/clr-installer -l 4
panic: No makePartCommand() implementation for: 

Error Trace:
storage.(*BlockDevice).WritePartitionTable()
     storage/ops.go:207
controller.Install()
     controller/controller.go:203


goroutine 7 [running]:
github.com/clearlinux/clr-installer/tui.(*Tui).Run(0xc0001551a0, 0xc00008cc00, 0xc0000b0d80, 0x16, 0x100, 0xc0000b0ce0, 0x17, 0x0, 0x0, 0x0, ...)
        /builddir/build/BUILD/clr-installer-1.1.0/.gopath/src/github.com/clearlinux/clr-installer/tui/tui.go:162 +0x670
main.main.func4(0xc0000cf7a0, 0xc00008cc00, 0xc0000b0d80, 0x16, 0xc000296a75, 0xc0000a3b40, 0xc0001a4070)
        /builddir/build/BUILD/clr-installer-1.1.0/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:243 +0x168
created by main.main
        /builddir/build/BUILD/clr-installer-1.1.0/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:237 +0x93d

# cat ~/clr-installer.log
2018/12/03 16:54:23 [DBG] Log Level set to LogLevelDebug (4)
2018/12/03 16:54:23 [INF] clr-installer: 1.1.0, built on 2018-11-30_18:09:00_UTC
2018/12/03 16:54:23 [DBG] Loading config file: /var/lib/clr-installer/clr-installer.yaml
2018/12/03 16:54:23 [DBG] PrivateIP: Found IP: 10.54.69.24, Private IP?: true
2018/12/03 16:54:23 [INF] NOTICE: Enabling Telemetry preferred by default on internal networks
2018/12/03 16:54:23 [DBG] localectl list-keymaps --no-pager
2018/12/03 16:54:23 [DBG] timedatectl list-timezones
2018/12/03 16:54:23 [DBG] locale -a
2018/12/03 16:54:23 [DBG] Unable to use language locale 'agr_PE.UTF-8'
2018/12/03 16:54:23 [DBG] Unable to use language locale 'ayc_PE.UTF-8'
2018/12/03 16:54:23 [DBG] Unable to use language locale 'ber_DZ.UTF-8'
2018/12/03 16:54:23 [DBG] Unable to use language locale 'ber_MA.UTF-8'
2018/12/03 16:54:23 [DBG] Unable to use language locale 'bhb_IN.UTF-8'
2018/12/03 16:54:23 [DBG] Unable to use language locale 'hne_IN.UTF-8'
2018/12/03 16:54:23 [DBG] Unable to use language locale 'miq_NI.UTF-8'
2018/12/03 16:54:23 [DBG] Unable to use language locale 'mjw_IN.UTF-8'
2018/12/03 16:54:23 [DBG] Unable to use language locale 'nhn_MX.UTF-8'
2018/12/03 16:54:23 [DBG] Unable to use language locale 'shs_CA.UTF-8'
2018/12/03 16:54:23 [DBG] Unable to use language locale 'the_NP.UTF-8'
2018/12/03 16:54:23 [DBG] Unable to use language locale 'unm_US.UTF-8'
2018/12/03 16:54:23 [DBG] Unable to use language locale 'yuw_PG.UTF-8'
2018/12/03 16:54:23 [DBG] lsblk --exclude 1,2,11 -J -b -O
2018/12/03 16:54:23 [DBG] partprobe /dev/sda
2018/12/03 16:54:23 [DBG] partprobe /dev/sdb
2018/12/03 16:54:24 [DBG] Warning: Not all of the space available to /dev/sdb appears to be used, you can fix the GPT to use all of the space (an extra 13533184 blocks) or continue with the current setting? 
2018/12/03 16:54:24 [DBG] ip route show
2018/12/03 16:54:24 [DBG] ip route show default
2018/12/03 16:54:24 [DBG] ip route show
2018/12/03 16:54:24 [DBG] ip route show default
2018/12/03 16:58:28 [DBG] lsblk --exclude 1,2,11 -J -b -O
2018/12/03 16:58:28 [DBG] partprobe /dev/sda
2018/12/03 16:58:28 [DBG] partprobe /dev/sdb
2018/12/03 16:58:29 [DBG] Warning: Not all of the space available to /dev/sdb appears to be used, you can fix the GPT to use all of the space (an extra 13533184 blocks) or continue with the current setting? 
2018/12/03 17:01:24 [DBG] ip route show
2018/12/03 17:01:24 [DBG] ip route show default
2018/12/03 17:01:24 [DBG] ip route show
2018/12/03 17:01:24 [DBG] ip route show default
2018/12/03 17:01:30 [INF] Testing connectivity
2018/12/03 17:01:30 [DBG] timeout --kill-after=10s 10s curl --no-sessionid -o /dev/null -s -f https://cdn.download.clearlinux.org/update/
2018/12/03 17:01:58 [INF] Running pre-install hooks
2018/12/03 17:01:58 [DBG] Created Local Telemetry server configuration file "/etc/telemetrics/telemetrics.conf"
2018/12/03 17:01:58 [DBG] telemctl restart
2018/12/03 17:01:58 [INF] Querying Clear Linux version
2018/12/03 17:01:58 [DBG] Clear Linux version: 26630
2018/12/03 17:01:58 [INF] Writing partition table to: sda
2018/12/03 17:01:58 [DBG] parted -s /dev/sda mklabel gpt
2018/12/03 17:01:58 [ERR] 

Error Trace:
storage.(*BlockDevice).WritePartitionTable()
     storage/ops.go:207
controller.Install()
     controller/controller.go:203
 No makePartCommand() implementation for: 
2018/12/03 17:01:58 [DBG] telem-record-gen --severity 3 --class org.clearlinux/clr-installer/tuipanic --event-id cc60fdf0c937f9ce669fa81d59447ea3 --payload version=1.1.0
No makePartCommand() implementation for: 

Error Trace:
storage.(*BlockDevice).WritePartitionTable()
     storage/ops.go:207
controller.Install()
     controller/controller.go:203

# lsblk
sda      8:0    0 447.1G  0 disk

```

**Comment by mdhorn** [comment]
This should be resolved using the latest Advanced Disk configuration option enabled the latest release clr-installer version 2.2.0   in [Clear Linux* OS release 31030](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz).
Latest release images are available here: https://clearlinux.org/downloads
