### ISSUE TITLE
panic: System Installation must provide a target media

### ISSUE THREAD

**Issue by jascott1** [clearlinux/clr-installer#485]
**Describe the bug**
clr-installer crashes with cloudguest.yaml direct from https://cdn.download.clearlinux.org/current/config/image/cloudguest.yaml

**To Reproduce**
1.`wget https://cdn.download.clearlinux.org/current/config/image/cloudguest.yaml`
2.`sudo clr-installer --config=~/cloudguest.yaml`

**Expected behavior**
cloudguest.img is created

**Screenshots**
```
Running pre-install hooks [success]
Error: Invalid configuration:
panic: System Installation must provide a target media

goroutine 1 [running]:
main.fatal(...)
        /builddir/build/BUILD/clr-installer-2.1.0/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:47
main.main()
        /builddir/build/BUILD/clr-installer-2.1.0/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:349 +0x2460

```

**Environment (please complete the following information):**
 - Clear Linux OS Version: 30550
 - Installer Version 2.1.0
 - Platform: Clear VM

**Additional context**

**Comment by mdhorn** [comment]
@jascott1 Please try using `${HOME}` instead of `~`.
I don't think the `~` in the path is being resolved by the go code.

**Comment by jascott1** [comment]
With `--tui` added I get a different stack trace:
```
sudo clr-installer --config=~/cloudguest.yaml --tui
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x749ba6]

goroutine 28 [running]:
github.com/clearlinux/clr-installer/tui.(*KernelPage).GetConfiguredValue(0xc0002c2840, 0x8ed6e0, 0xc0002c2840)
        /builddir/build/BUILD/clr-installer-2.1.0/.gopath/src/github.com/clearlinux/clr-installer/tui/kernel_selection.go:29 +0x16
github.com/clearlinux/clr-installer/tui.(*MenuPage).Activate(0xc0002c2370)
        /builddir/build/BUILD/clr-installer-2.1.0/.gopath/src/github.com/clearlinux/clr-installer/tui/menu.go:80 +0x299
github.com/clearlinux/clr-installer/tui.(*Tui).gotoPage(0xc00009d040, 0xd, 0x0, 0x0)
        /builddir/build/BUILD/clr-installer-2.1.0/.gopath/src/github.com/clearlinux/clr-installer/tui/tui.go:184 +0xb0
github.com/clearlinux/clr-installer/tui.(*Tui).Run(0xc00009d040, 0xc0000dc1e0, 0xc000094f80, 0x16, 0x100, 0xc000094e60, 0x17, 0x7ffff2fccc7b, 0x11, 0x0, ...)
        /builddir/build/BUILD/clr-installer-2.1.0/.gopath/src/github.com/clearlinux/clr-installer/tui/tui.go:130 +0x5a5
main.main.func5(0xc0000c9900, 0xc0000dc1e0, 0xc000094f80, 0x16, 0xc0001f9e48, 0xc0001425e0, 0xc000074240, 0xc00015c070)
        /builddir/build/BUILD/clr-installer-2.1.0/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:311 +0x198
created by main.main
        /builddir/build/BUILD/clr-installer-2.1.0/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:305 +0x1239

```

**Comment by mdhorn** [comment]
@jascott1 Actually, what is happening is that the `~` is resolved after the sudo is invoked and it is using root's home directory instead of your own.
Please use either the full path to the configuration file.

**Comment by jascott1** [comment]
Thanks @mdhorn ! That fixed it. FYI I copied that `~/` from the readme:
https://github.com/clearlinux/clr-installer/blob/master/Readme.md#using-mass-installer

**Comment by mdhorn** [comment]
@jascott1 Thank you for pointing out that error in the Readme file.
A fix is in progress: https://github.com/clearlinux/clr-installer/pull/486
